### ISSUE TITLE
Error: Matrix not positve definite 

### ISSUE THREAD

**Issue by FelixHIS** [ciuccislab/GP-DRT#13]
I was trying to use the GP-DRT with my EIS data, the optimization in 3) of the example 4 runs into an error as the cholesky decomposition in line 173 of GP_DRT.py does not work. The matrix K_im_full seems to be not always positive definite, depending on the values of the hyperparameters: sigma_n, sigma_f and ell. Do ou have any Idea how this could prevented?

**Comment by frank-ccc** [comment]
Sorry for the late reply. We are aware of this issue. It is due to K_im, and its interplay with the optimizer, which may go to unfeasible regions. We can fix it by adding some exception handling. Please allow us a few days to modify it. @jiapeng-liu

**Comment by ciuccislab** [comment]
Dear @FelixHIS sorry for the very late reply. Jiapeng @jiapeng-liu added some exception handling in a new notebook ex6_exception_handling.ipynb Please let us know if this works for you.

**Comment by FelixHIS** [comment]
Hello @ciuccislab, @jiapeng-liu , @frank-ccc   thank you very much for the proposed solution. I tried it out in my implementation (which is a copy of your notebook ex4 in this part) and it turns out that the code is caught in the while loop, trying to find an appropriate value for theta. To avoid this I wondered if there is a way to know which values of theta are of limits an exclude them from the search? Do you have any ideas on that?

**Comment by frank-ccc** [comment]
Hi @FelixHIS, we would need to look at your implementation in more detail. Would you be able to contact me separately via email?

**Comment by FelixHIS** [comment]
Hello, yes of course: felix.hildenbrand@isea.rwth-aachen.de . Thank you for the fast response. I could also post my code here?

**Comment by frank-ccc** [comment]
Thanks a lot, @FelixHIS. I have written to you. To streamline the discussion, I suggest we post an amended notebook and solution once we have figured out why your code isn't working.

**Comment by ciuccislab** [comment]
The new update solves this issue.
